### kotlin suspend method
GET http://localhost:8181/kt/hello

### kotlin Flow as Stream
GET http://localhost:8181/kt/stream1

### kotlin Flow as channel
GET http://localhost:8181/kt/channel1

### Get
GET http://localhost:8180/demo